version: 2.1
orbs:
  demo-orbs: demo-orbs/e2e-test@1.0.3
  build-tools: circleci/build-tools@3.0.0  

workflows:
  sanity-and-functional:
    jobs:
      - demo-orbs/run-e2e-tests:
          notify_success: true
      - hold-functional:
          type: approval      
      - demo-orbs/run-e2e-tests:
          notify_success: true
          suite: functional
          requires: 
            - hold-functional
